// examples/integration-templates/sveltekit/src/lib/PageView.svelte
<script lang="ts">
  import type { ContentVedaPage } from '$lib/contentveda';
  import BlockRenderer from '$lib/BlockRenderer.svelte';
  import SiteMenu from '$lib/SiteMenu.svelte';

  let { page, mode }: { page: ContentVedaPage; mode: string } = $props();

  // Menus are assigned to slots in CMS → Navigation; the page can override them.
  const header = $derived(page.navigation.header || page.navigation.mobile || []);
  const footer = $derived(page.navigation.footer || []);
</script>

<svelte:head>
  <title>{page.title}</title>
</svelte:head>

{#if header.length}
  <header class="cv-site-header">
    <nav aria-label="Main"><SiteMenu items={header} /></nav>
  </header>
{/if}

<main class="cv-page" data-cv-slug={page.slug} data-cv-api={mode}>
  {#each page.content as block (block.id)}
    <section class="cv-floor" data-cv-type={block.type}>
      {#if block.properties.header.title}
        <div class="cv-floor-header">
          <div>
            <h2>{block.properties.header.title}</h2>
            {#if block.properties.header.subtitle}<p>{block.properties.header.subtitle}</p>{/if}
          </div>
          {#if block.properties.header.moreLink}
            <a href={block.properties.header.moreLink.url}>
              {block.properties.header.moreLink.label} {block.properties.header.moreLink.icon || '→'}
            </a>
          {/if}
        </div>
      {/if}
      <BlockRenderer {block} />
    </section>
  {/each}
</main>

{#if footer.length}
  <footer class="cv-site-footer">
    <nav aria-label="Footer"><SiteMenu items={footer} /></nav>
  </footer>
{/if}

// examples/integration-templates/nextjs/src/components/PageView.tsx
import type { ContentVedaPage } from '@/lib/contentveda';
import { config } from '@/lib/config';
import BlockRenderer from './BlockRenderer';
import SiteMenu from './SiteMenu';

export default function PageView({ page }: { page: ContentVedaPage }) {
  // Menus are assigned to slots in CMS → Navigation; the page can override them.
  const header = page.navigation.header || page.navigation.mobile || [];
  const footer = page.navigation.footer || [];

  return (
    <>
      {header.length ? (
        <header className="cv-site-header">
          <nav aria-label="Main"><SiteMenu items={header} /></nav>
        </header>
      ) : null}

      <main className="cv-page" data-cv-slug={page.slug} data-cv-api={config.mode}>
        {page.content.map((block) => (
          <section key={block.id} className="cv-floor" data-cv-type={block.type}>
            {block.properties.header.title ? (
              <div className="cv-floor-header">
                <div>
                  <h2>{block.properties.header.title}</h2>
                  {block.properties.header.subtitle ? <p>{block.properties.header.subtitle}</p> : null}
                </div>
                {block.properties.header.moreLink ? (
                  <a href={block.properties.header.moreLink.url}>
                    {block.properties.header.moreLink.label} {block.properties.header.moreLink.icon || '→'}
                  </a>
                ) : null}
              </div>
            ) : null}
            <BlockRenderer block={block} />
          </section>
        ))}
      </main>

      {footer.length ? (
        <footer className="cv-site-footer">
          <nav aria-label="Footer"><SiteMenu items={footer} /></nav>
        </footer>
      ) : null}
    </>
  );
}
